### ISSUE TITLE
Build error - strange copy dependencies

### ISSUE THREAD

**Issue by jiriryba** [MarcStan/Resource.Embedder#5] opened 2016-07-19 16:42 UTC
Hi, can you please help me ?  I came across a problem with build using Resource.Embedder. 
For uknown reason in one of our project the build fails with the report attached.
Project Offer depends on project BusinessLayer2 and each one has its own resources and has RE nuget applied. Project BusinessLayer2 is built correctly, but for project Offers when the MSBuild launches "EmbedderTarget" this one is trying (why? Shouldn't it look just for Offers) to lookup **BusinessLayer2** assembly in project directories of Offers (bin\Debug\). But the assembly would be copied there with the Target "_CopyFilesMarkedCopyLocal" which follows right after "EmbedderTarget".

Log:
`11>Done building target "GenerateSatelliteAssemblies" in project "Offers.csproj".: (TargetId:228)
11>Target "EmbedderTarget: (TargetId:229)" in file "C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets" from project "C:\Vyvoj2015\AS\AS\Offers\Offers.csproj" (target "CreateSatelliteAssemblies" depends on it):
11>Using "ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask" task from assembly "C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\..\ResourceEmbedder.MsBuild.dll".
11>Task "ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask" (TaskId:127)
11>  Task Parameter:AssemblyPath=obj\Debug\AS.Offers.dll (TaskId:127)
11>  Task Parameter:ProjectDirectory=C:\Vyvoj2015\AS\AS\Offers\ (TaskId:127)
11>  Task Parameter:TargetPath=C:\Vyvoj2015\AS\AS\Offers\bin\Debug\AS.Offers.dll (TaskId:127)
11>  Rewritting pdb (TaskId:127)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018: The "ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask" task failed unexpectedly.
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'AS.BusinessLayer2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.TypeReference.Resolve()
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.AddTypeDefs()
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.BuildTypes()
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.MetadataBuilder.BuildModule()
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at ResourceEmbedder.Core.Cecil.CecilBasedAssemblyModifier.Save() in C:\Projects\Resource.Embedder\src\modules\ResourceEmbedder.Core\ResourceEmbedder.Core\Cecil\CecilBasedAssemblyModifier.cs:line 103
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at ResourceEmbedder.Core.Cecil.CecilBasedAssemblyModifier.Dispose() in C:\Projects\Resource.Embedder\src\modules\ResourceEmbedder.Core\ResourceEmbedder.Core\Cecil\CecilBasedAssemblyModifier.cs:line 76
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask.Execute() in C:\Projects\Resource.Embedder\src\modules\ResourceEmbedder.MsBuild\ResourceEmbedder.MsBuild\SatelliteAssemblyEmbedderTask.cs:line 82
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
11>C:\Vyvoj2015\AS\AS\packages\Resource.Embedder.1.1.1.0\build\Resource.Embedder.targets(46,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
11>Done executing task "ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask" -- FAILED. (TaskId:127)
11>Done building target "EmbedderTarget" in project "Offers.csproj" -- FAILED.: (TargetId:229)
11>Target "_CheckForCompileOutputs: (TargetId:230)" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets" from project "C:\Vyvoj2015\AS\AS\Offers\Offers.csproj" (target "_CleanGetCurrentAndPriorFileWrites" depends on it):
11>Added Item(s): FileWrites=obj\Debug\AS.Offers.dll
11>Set Property: _DocumentationFileProduced=false
11>Added Item(s): FileWrites=obj\Debug\AS.Offers.pdb`

BTW Sorry, for my english ;)

**Comment by MarcStan** [comment] 2016-07-19 20:59
The crash happens inside AssemblyDefinition.Write which is a method from [Mono.Cecil](https://github.com/jbevain/cecil/).

I found [this issue](https://github.com/jbevain/cecil/issues/236) on their page which might be related.

Is what they write true for your BusinessLayer2 project?

Also is it possible for you to create a sample solution where the crash happens so I can debug through it?

**Comment by jiriryba** [comment] 2016-07-20 08:11
Hi, thank you for fast reply. 
Unfortunately both projects (BusinessLayer2 / Offers) are huge and I have no time to analyze their code in depth. 
I event tried to make sample project but it compiles just fine.
The linked Issue is same in that way that the referenced library is not present at output direktory of  project analyzed by cecil. But as I understood it was already solved in cecil since Aug 28 2015...

Another mystery is that on our build server this compiles just fine (clean build) but on dev. machines we have this problem (clean build, even tried to delete all files and get latest version, result is the same).

I am sorry  I have no time to go in depth, so I am afraid I would have to stick with ilmerge or let resource dlls alone. 
Thanks anyway !

**Comment by MarcStan** [comment] 2016-07-20 08:57
Yes but Cecil's last release (Cecil v0.9.6) was on April 25th 2015 so the bugfix is not yet in the version that Resource.Embedder uses.

Supposedly there will be a new release "soon".

I'll update my package then and comment here again so you get a notification, hopefully this will fix your issue then,

**Comment by jiriryba** [comment] 2016-07-20 09:00
thanks !

**Comment by mateusz-polak** [comment] 2016-08-17 07:34
Hi Marc,

First of all - you did a great job with this tool. Saved me a lot of time. I appreciate that.

I encountered same (I guess) issue and I think it's on your side.
Just to bold it from @jiriryba's comment, it's about resolving references of the current project:

**_The "ResourceEmbedder.MsBuild.SatelliteAssemblyEmbedderTask" task failed unexpectedly.
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'XXX'_**

I've investigated the problem a bit, and found that you inject the resources in intermediate assembly of the project in _**obj/$(Configuration)**_ just after **_GenerateSatelliteAssemblies_** target. In your task _**SatelliteAssemblyEmbedderTask**_ you use Cecil to actually load the assembly (or whatever happens under the hood) and if the project (so the injected assembly) has any external dependencies that need to be copied to the _**OutputPath**_ you use this output path to resolve them.

Line 69 in **SatelliteAssemblyEmbedderTask.cs** 
_var searchDirs = new[] { new FileInfo(TargetPath).DirectoryName };_

In that case it would be _**bin/$(Configuration)**_
This is ok as long as you've built your project before and this directory is not empty. The references sit there and will be properly resolved. If you, however, make a clean (i.e. by hitting "Rebuild" in VS), all dependencies in _**bin/$(Configuration)**_ will be removed and during execution of your task there will be nothing to resolve.

Personally, I think it's a right way to place the _**SatelliteAssemblyEmbedderTask**_ where it is, so just after **_GenerateSatelliteAssemblies_** and before **_CopyFilesMarkedCopyLocal_**. The way of resolving private dependencies must be changed, because you cannot relay on _**bin/$(Configuration)**_ at the moment your task is executed. Maybe you could use the **@Reference** property in msbuild and use all those reference's paths marked as private, i.e:

    <Reference Include="ServiceStack, Version=3.9.71.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\ServiceStack.3.9.71\lib\net35\ServiceStack.dll</HintPath>
      <Private>False</Private>
    </Reference>

Mateusz

**Comment by MarcStan** [comment] 2016-08-17 09:24
Thanks for your help.

I will see if I can find a way to add all hint path of private references to the search directory list. This should then allow all references to be properly resolved.

**Comment by mateusz-polak** [comment] 2016-08-17 11:25
Just a small update on that issue:
Some strange things... Basically, when the problem ocurred I was able to reproduce it using your 2nd NuGet package: **Resource.Embeddere.Core**. I've reimplemented steps from your **SatelliteAssemblyEmbedderTask** in a simple console application, and tested two scenarios, but for my particular, quite complex project. Than, as expected, an exact error came when the _**bin\Debug**_ was empty, and the injection was successful when the _**bin\Debug**_ contained all the external references.

After that, I tried to reproduce the error for a much simpler scenario. I made a dummy console app, some DLLs as refs (referred just as DLLs from path, as other project in the same solution, and as some DLLs from NuGet). Than I pulled your **_Resource.Embedder_** from NuGet and it worked for Build/Rebuild like a charm. All my resources were correctly embedded.
This is somehow unexpected behavior according to my previous theory... :)

**Comment by MarcStan** [comment] 2016-08-17 11:33
Yes, @jiriryba reported the same behaviour.

I linked the issue from Cecil above (and [here again](https://github.com/jbevain/cecil/issues/236)).

I assume your complex project contains **some code that forces Cecil to actually look up the reference** whereas the small sample projects don't have to look for the reference (and will instead just assume that it exists).

By forcing the lookup the resource embedder will fail because I am not letting it look in the right places.

I'm currently working on getting MSBuild to forward the project references to my task so I can add it the the searchDirs list.

**Comment by mateusz-polak** [comment] 2016-08-17 11:46
Yep, you hit the target.

as @jbevain wrote [here](https://github.com/jbevain/cecil/issues/236):
> Cecil needs to resolve a TypeRef to write it properly:
> 
>    - When you have a const field with a TypeRef to an enum.

So, in my dummy solution, I added an enum to my referenced project, and in my main project made a const from that enum. As a result I have an error now.

**Comment by MarcStan** [comment] 2016-08-17 14:28
@jiriryba @mateusz-polak 

I just uploaded v1.2 on nuget. This version will now also look for reference assemblies at their output location using the MSBuild ReferencePath property (instead of just at the projects own output location).

Can you check with your projects if this fixes your issue?

I am now also logging "Looking for references in: ..." (visible in the Output Window/Build Tab) of Visual Studio.

It contains a list of all directories that will be searched for assemblies. It should now also contain all the directories of your reference files that aren't marked as CopyLocal/Private: True.

**Comment by mateusz-polak** [comment] 2016-08-17 15:10
Looking good! 
Worked for reference as DLL and a sub-project. And I can see the culture specific resources in my end-app so the injection was for sure successful.

Many thanks for quick response!
Thumb up! :)

**Closed** 2016-08-22 11:38 UTC
